# Numpy
Numpy jest pakietem, do obliczeń matematycznych, szczególnie na macierzach danych.

Dokumentacja: https://numpy.org/doc/stable/

In [1]:
# import biblioteki
import numpy as np

In [2]:
#pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
# Tworzenie macierzy jednowymiarowej z macierzy
macierz_1d = np.array([10,20,30,40])
macierz_1d


array([10, 20, 30, 40])

In [5]:
type(macierz_1d)

numpy.ndarray

In [6]:
# Wyciągnięcie pierwszego elementu
macierz_1d[0]

np.int64(10)

In [7]:
# Wyciągnięcie ostatniego elementu
macierz_1d[-1]

np.int64(40)

In [8]:
# Zmiana wartości
macierz_1d[0] = 100
macierz_1d

array([100,  20,  30,  40])

In [9]:
# Dodanie wartości
macierz_1d = np.append(macierz_1d, 50)
macierz_1d

array([100,  20,  30,  40,  50])

In [10]:
# Macierz dwuwymiarowa
macierz_2d = np.array([[10,20,30,40],[100,200,300,400],[1000,2000,3000,4000]])
macierz_2d

array([[  10,   20,   30,   40],
       [ 100,  200,  300,  400],
       [1000, 2000, 3000, 4000]])

In [11]:
# dwa indeksy: wiersz - kolumna
macierz_2d[0][1]

np.int64(20)

Wartości puste możemy wpisywać jako np.nan

In [12]:
macierz_2d = np.array([[10,20,np.nan, 40],[100,200,300,np.nan],[1000,2000,3000,4000]])

In [13]:
macierz_2d

array([[  10.,   20.,   nan,   40.],
       [ 100.,  200.,  300.,   nan],
       [1000., 2000., 3000., 4000.]])