# Numpy - operacje matematyczne

Zaletą korzystania z macierzy są możliwości przeliczeń matematycznych, które mogą nie działać w standardowej liście.

In [1]:
import numpy as np

In [2]:
# Potęgowanie - lista
lista = [10,20,30,40]
lista ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [3]:
# potegowanie macierz
np.array(lista) ** 2

array([ 100,  400,  900, 1600])

In [4]:
macierz = np.array(lista)

In [7]:
# Dodawanie liczby do elementów
macierz + 2


array([12, 22, 32, 42])

In [10]:
# Odejmowanie liczby od elementów
macierz - 2

array([ 8, 18, 28, 38])

In [11]:
# Mnożenie elementów
macierz * 2

array([20, 40, 60, 80])

In [12]:
# Dzielenie elementów
macierz / 3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333])

In [13]:
# suma elementów
np.sum(macierz)

np.int64(100)

In [14]:
np.sum(lista)

np.int64(100)

In [15]:
# średnia
np.mean(macierz)

np.float64(25.0)

In [16]:
np.mean(lista)

np.float64(25.0)

In [18]:
macierz_new = macierz - 20
macierz_new

array([-10,   0,  10,  20])

In [19]:
# Wartosc bezwzgledna
np.abs(macierz_new)

array([10,  0, 10, 20])

In [20]:
# Najwyższa wartość
np.amax(macierz_new)

np.int64(20)

In [21]:
# Najniższa wartość
np.amin(macierz_new)

np.int64(-10)

In [22]:
# Indeks elementu o najwyższej wartości
np.argmax(macierz_new)

np.int64(3)

In [23]:
# Indeks elementu o najniższej wartości
np.argmin(macierz_new)

np.int64(0)

In [24]:
#sufit
macierz_float = np.array([1.4,2.8,2.99,5.79])

In [25]:
np.ceil(macierz_float)

array([2., 3., 3., 6.])

In [26]:
# Suma narastająca
np.cumsum(macierz_float)

array([ 1.4 ,  4.2 ,  7.19, 12.98])

In [27]:
# e^x
np.exp(macierz_float)

array([  4.05519997,  16.44464677,  19.88568249, 327.01302438])

In [28]:
# Mediana
np.median(macierz_float)

np.float64(2.895)

In [37]:
# Losowanie z przedziału [0,1)
np.random.random()

0.0703537473010154